(cl:defpackage traj_plan-srv
  (:use )
  (:export
   "JOINTINTERPOLATION"
   "<JOINTINTERPOLATION-REQUEST>"
   "JOINTINTERPOLATION-REQUEST"
   "<JOINTINTERPOLATION-RESPONSE>"
   "JOINTINTERPOLATION-RESPONSE"
  ))

