controller_list:
  - name: fake_puma_560_controller
    type: $(arg fake_execution_type)
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
initial:  # Define initial robot poses.
  - group: puma_560
    pose: zero_pos