// Generated by gencpp from file traj_plan/JointInterpolationResponse.msg
// DO NOT EDIT!


#ifndef TRAJ_PLAN_MESSAGE_JOINTINTERPOLATIONRESPONSE_H
#define TRAJ_PLAN_MESSAGE_JOINTINTERPOLATIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <trajectory_msgs/JointTrajectory.h>

namespace traj_plan
{
template <class ContainerAllocator>
struct JointInterpolationResponse_
{
  typedef JointInterpolationResponse_<ContainerAllocator> Type;

  JointInterpolationResponse_()
    : result()  {
    }
  JointInterpolationResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef  ::trajectory_msgs::JointTrajectory_<ContainerAllocator>  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::traj_plan::JointInterpolationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traj_plan::JointInterpolationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct JointInterpolationResponse_

typedef ::traj_plan::JointInterpolationResponse_<std::allocator<void> > JointInterpolationResponse;

typedef boost::shared_ptr< ::traj_plan::JointInterpolationResponse > JointInterpolationResponsePtr;
typedef boost::shared_ptr< ::traj_plan::JointInterpolationResponse const> JointInterpolationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traj_plan::JointInterpolationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traj_plan::JointInterpolationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::traj_plan::JointInterpolationResponse_<ContainerAllocator1> & lhs, const ::traj_plan::JointInterpolationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::traj_plan::JointInterpolationResponse_<ContainerAllocator1> & lhs, const ::traj_plan::JointInterpolationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace traj_plan

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::traj_plan::JointInterpolationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_plan::JointInterpolationResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traj_plan::JointInterpolationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traj_plan::JointInterpolationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_plan::JointInterpolationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_plan::JointInterpolationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traj_plan::JointInterpolationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a36292cb6aa1b89fd75fe9b833aa4bc5";
  }

  static const char* value(const ::traj_plan::JointInterpolationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa36292cb6aa1b89fULL;
  static const uint64_t static_value2 = 0xd75fe9b833aa4bc5ULL;
};

template<class ContainerAllocator>
struct DataType< ::traj_plan::JointInterpolationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traj_plan/JointInterpolationResponse";
  }

  static const char* value(const ::traj_plan::JointInterpolationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traj_plan::JointInterpolationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trajectory_msgs/JointTrajectory result\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectory\n"
"Header header\n"
"string[] joint_names\n"
"JointTrajectoryPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectoryPoint\n"
"# Each trajectory point specifies either positions[, velocities[, accelerations]]\n"
"# or positions[, effort] for the trajectory to be executed.\n"
"# All specified values are in the same order as the joint names in JointTrajectory.msg\n"
"\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"float64[] effort\n"
"duration time_from_start\n"
;
  }

  static const char* value(const ::traj_plan::JointInterpolationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traj_plan::JointInterpolationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointInterpolationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traj_plan::JointInterpolationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traj_plan::JointInterpolationResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAJ_PLAN_MESSAGE_JOINTINTERPOLATIONRESPONSE_H
