// Generated by gencpp from file traj_plan/JointInterpolationRequest.msg
// DO NOT EDIT!


#ifndef TRAJ_PLAN_MESSAGE_JOINTINTERPOLATIONREQUEST_H
#define TRAJ_PLAN_MESSAGE_JOINTINTERPOLATIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <trajectory_msgs/JointTrajectory.h>

namespace traj_plan
{
template <class ContainerAllocator>
struct JointInterpolationRequest_
{
  typedef JointInterpolationRequest_<ContainerAllocator> Type;

  JointInterpolationRequest_()
    : waypoints()  {
    }
  JointInterpolationRequest_(const ContainerAllocator& _alloc)
    : waypoints(_alloc)  {
  (void)_alloc;
    }



   typedef  ::trajectory_msgs::JointTrajectory_<ContainerAllocator>  _waypoints_type;
  _waypoints_type waypoints;





  typedef boost::shared_ptr< ::traj_plan::JointInterpolationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traj_plan::JointInterpolationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct JointInterpolationRequest_

typedef ::traj_plan::JointInterpolationRequest_<std::allocator<void> > JointInterpolationRequest;

typedef boost::shared_ptr< ::traj_plan::JointInterpolationRequest > JointInterpolationRequestPtr;
typedef boost::shared_ptr< ::traj_plan::JointInterpolationRequest const> JointInterpolationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traj_plan::JointInterpolationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traj_plan::JointInterpolationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::traj_plan::JointInterpolationRequest_<ContainerAllocator1> & lhs, const ::traj_plan::JointInterpolationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.waypoints == rhs.waypoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::traj_plan::JointInterpolationRequest_<ContainerAllocator1> & lhs, const ::traj_plan::JointInterpolationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace traj_plan

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::traj_plan::JointInterpolationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_plan::JointInterpolationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traj_plan::JointInterpolationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traj_plan::JointInterpolationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_plan::JointInterpolationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_plan::JointInterpolationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traj_plan::JointInterpolationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c462000a737060e77b8a22d9b459ddec";
  }

  static const char* value(const ::traj_plan::JointInterpolationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc462000a737060e7ULL;
  static const uint64_t static_value2 = 0x7b8a22d9b459ddecULL;
};

template<class ContainerAllocator>
struct DataType< ::traj_plan::JointInterpolationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traj_plan/JointInterpolationRequest";
  }

  static const char* value(const ::traj_plan::JointInterpolationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traj_plan::JointInterpolationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trajectory_msgs/JointTrajectory waypoints\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectory\n"
"Header header\n"
"string[] joint_names\n"
"JointTrajectoryPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectoryPoint\n"
"# Each trajectory point specifies either positions[, velocities[, accelerations]]\n"
"# or positions[, effort] for the trajectory to be executed.\n"
"# All specified values are in the same order as the joint names in JointTrajectory.msg\n"
"\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"float64[] effort\n"
"duration time_from_start\n"
;
  }

  static const char* value(const ::traj_plan::JointInterpolationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traj_plan::JointInterpolationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointInterpolationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traj_plan::JointInterpolationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traj_plan::JointInterpolationRequest_<ContainerAllocator>& v)
  {
    s << indent << "waypoints: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.waypoints);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAJ_PLAN_MESSAGE_JOINTINTERPOLATIONREQUEST_H
