// Generated by gencpp from file traj_plan/JointInterpolation.msg
// DO NOT EDIT!


#ifndef TRAJ_PLAN_MESSAGE_JOINTINTERPOLATION_H
#define TRAJ_PLAN_MESSAGE_JOINTINTERPOLATION_H

#include <ros/service_traits.h>


#include <traj_plan/JointInterpolationRequest.h>
#include <traj_plan/JointInterpolationResponse.h>


namespace traj_plan
{

struct JointInterpolation
{

typedef JointInterpolationRequest Request;
typedef JointInterpolationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JointInterpolation
} // namespace traj_plan


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::traj_plan::JointInterpolation > {
  static const char* value()
  {
    return "69c5258a1c5a9248843418c54aa9d57a";
  }

  static const char* value(const ::traj_plan::JointInterpolation&) { return value(); }
};

template<>
struct DataType< ::traj_plan::JointInterpolation > {
  static const char* value()
  {
    return "traj_plan/JointInterpolation";
  }

  static const char* value(const ::traj_plan::JointInterpolation&) { return value(); }
};


// service_traits::MD5Sum< ::traj_plan::JointInterpolationRequest> should match
// service_traits::MD5Sum< ::traj_plan::JointInterpolation >
template<>
struct MD5Sum< ::traj_plan::JointInterpolationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::traj_plan::JointInterpolation >::value();
  }
  static const char* value(const ::traj_plan::JointInterpolationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_plan::JointInterpolationRequest> should match
// service_traits::DataType< ::traj_plan::JointInterpolation >
template<>
struct DataType< ::traj_plan::JointInterpolationRequest>
{
  static const char* value()
  {
    return DataType< ::traj_plan::JointInterpolation >::value();
  }
  static const char* value(const ::traj_plan::JointInterpolationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::traj_plan::JointInterpolationResponse> should match
// service_traits::MD5Sum< ::traj_plan::JointInterpolation >
template<>
struct MD5Sum< ::traj_plan::JointInterpolationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::traj_plan::JointInterpolation >::value();
  }
  static const char* value(const ::traj_plan::JointInterpolationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_plan::JointInterpolationResponse> should match
// service_traits::DataType< ::traj_plan::JointInterpolation >
template<>
struct DataType< ::traj_plan::JointInterpolationResponse>
{
  static const char* value()
  {
    return DataType< ::traj_plan::JointInterpolation >::value();
  }
  static const char* value(const ::traj_plan::JointInterpolationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAJ_PLAN_MESSAGE_JOINTINTERPOLATION_H
