// Generated by gencpp from file traj_plan/PoseStampedArray.msg
// DO NOT EDIT!


#ifndef TRAJ_PLAN_MESSAGE_POSESTAMPEDARRAY_H
#define TRAJ_PLAN_MESSAGE_POSESTAMPEDARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace traj_plan
{
template <class ContainerAllocator>
struct PoseStampedArray_
{
  typedef PoseStampedArray_<ContainerAllocator> Type;

  PoseStampedArray_()
    : data()  {
    }
  PoseStampedArray_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::PoseStamped_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::traj_plan::PoseStampedArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traj_plan::PoseStampedArray_<ContainerAllocator> const> ConstPtr;

}; // struct PoseStampedArray_

typedef ::traj_plan::PoseStampedArray_<std::allocator<void> > PoseStampedArray;

typedef boost::shared_ptr< ::traj_plan::PoseStampedArray > PoseStampedArrayPtr;
typedef boost::shared_ptr< ::traj_plan::PoseStampedArray const> PoseStampedArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traj_plan::PoseStampedArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traj_plan::PoseStampedArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::traj_plan::PoseStampedArray_<ContainerAllocator1> & lhs, const ::traj_plan::PoseStampedArray_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::traj_plan::PoseStampedArray_<ContainerAllocator1> & lhs, const ::traj_plan::PoseStampedArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace traj_plan

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::traj_plan::PoseStampedArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_plan::PoseStampedArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traj_plan::PoseStampedArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traj_plan::PoseStampedArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_plan::PoseStampedArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_plan::PoseStampedArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traj_plan::PoseStampedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f787417d6b8b8074c0c0075d0c89d8f8";
  }

  static const char* value(const ::traj_plan::PoseStampedArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf787417d6b8b8074ULL;
  static const uint64_t static_value2 = 0xc0c0075d0c89d8f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::traj_plan::PoseStampedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traj_plan/PoseStampedArray";
  }

  static const char* value(const ::traj_plan::PoseStampedArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traj_plan::PoseStampedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped[] data\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::traj_plan::PoseStampedArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traj_plan::PoseStampedArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseStampedArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traj_plan::PoseStampedArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traj_plan::PoseStampedArray_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAJ_PLAN_MESSAGE_POSESTAMPEDARRAY_H
